<a href="https://colab.research.google.com/github/arumlim/eileen/blob/master/01_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

### array 생성하기

In [7]:
# 1차원
array_1D = np.array([1,2,3])
print(array_1D)

[1 2 3]


In [ ]:
# 2차원 array
array_2D = np.array([[1,2,3],
               [4,5,6]])
print(array_2D)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3차원 array
array_3D = np.array([[[1,2,3],
                [4,5,6]],
               [[1,2,3],
                [4,5,6]]])
print(array_3D)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### array 기초 통계량 활용하기

In [ ]:
array_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array_2D.max()

6

In [ ]:
array_2D.mean()

3.5

In [ ]:
array_2D.min()

1

In [ ]:
array_2D.sum()

21

### array 모양 변경하기 

In [ ]:
reshape_array = np.arange(15)
print(reshape_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
reshape_array = reshape_array.reshape(3, 5)
print(reshape_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
reshape_array.shape

(3, 5)

In [ ]:
reshape_array.ndim

2

In [ ]:
reshape_array.size

15

In [ ]:
array_1D = np.arange(0, 100, 5)
print(array_1D)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
reshape_array_3D = array_1D.reshape(2, 2, 5)
reshape_array_3D

array([[[ 0,  5, 10, 15, 20],
        [25, 30, 35, 40, 45]],

       [[50, 55, 60, 65, 70],
        [75, 80, 85, 90, 95]]])

### numpy array operation

In [ ]:
array1 = np.array([[1, 0],
               [0, 1]])
array2 = np.array([[1, 2],
               [3, 4]])

In [ ]:
array1 + array2

array([[2, 2],
       [3, 5]])

In [ ]:
array1 - array2

array([[ 0, -2],
       [-3, -3]])

In [ ]:
array1 * array2

array([[1, 0],
       [0, 4]])

In [ ]:
array1 / array2

array([[1.  , 0.  ],
       [0.  , 0.25]])

In [ ]:
array1 + 1

array([[2, 1],
       [1, 2]])

In [ ]:
array1 - 1

array([[ 0, -1],
       [-1,  0]])

In [ ]:
array1 * 2

array([[2, 0],
       [0, 2]])

In [ ]:
array1 / 2

array([[0.5, 0. ],
       [0. , 0.5]])

In [ ]:
np.dot(array1, array2)

array([[1, 2],
       [3, 4]])

In [ ]:
n3 = np.arange(12).reshape(3,4)
print(n3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(n3.max())     # 최대값
print(n3.min())     # 최소값
print(n3.sum())     # 전체 합
print(n3.mean())     # 평균값
print(n3.std())     # 표준편차
print(n3.var())     # 분산
print(n3.cumsum())     # 각 원소의 누적 합
print(n3.cumprod())     # 각 원소의 누적 곱

11
0
66
5.5
3.452052529534663
11.916666666666666
[ 0  1  3  6 10 15 21 28 36 45 55 66]
[0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
n3.sum(axis=0)     # 열 합계

array([12, 15, 18, 21])

In [ ]:
n3.sum(axis=1)     # 행 합계

array([ 6, 22, 38])

In [ ]:
n3.max(axis=1)     # 각 행에서 최대값

array([ 3,  7, 11])

In [ ]:
n3.mean(axis=0)     # 각 열의 평균값

array([4., 5., 6., 7.])

### array stack

In [ ]:
v1 = np.arange(11, 16)
print(v1)
v2 = v1 + 10
print(v2)
v3 = v2 + 10
print(v3)

[11 12 13 14 15]
[21 22 23 24 25]
[31 32 33 34 35]


In [ ]:
v = np.vstack((v1, v2))
v = np.vstack((v, v3))
print(v)

[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]]


In [ ]:
v = np.array([[11, 12, 13, 14, 15],
              [21, 22, 23, 24, 25],
              [31, 32, 33, 34, 35],
              [41, 42, 43, 44, 45]])

In [ ]:
v[1, 2]

23

In [ ]:
v[1][2]

23

In [ ]:
v[:, 1]

array([12, 22, 32, 42])

In [ ]:
v[1:3, 1]

array([22, 32])

In [ ]:
v[1, :]

array([21, 22, 23, 24, 25])