<a href="https://colab.research.google.com/github/arumlim/eileen/blob/master/1128_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

### array 생성하기

In [ ]:
# 1차원
array_1D = np.array([1,2,3])
print(array_1D)

[1 2 3]


In [ ]:
# 2차원 array
array_2D = np.array([[1,2,3],
               [4,5,6]])
print(array_2D)

[[1 2 3]
 [4 5 6]]


In [ ]:
array_2D = np.array([[6,1,2],
                    [3,6,9],
                    [4,7,8]])
print(array_2D)

[[6 1 2]
 [3 6 9]
 [4 7 8]]


In [ ]:
# 3차원 array
array_3D = np.array([[[1,2,3],
                [4,5,6]],
               [[1,2,3],
                [4,5,6]]])
print(array_3D)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### array 기초 통계량 활용하기

In [ ]:
array_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array_2D.max()

9

In [ ]:
array_2D.mean()

5.111111111111111

In [ ]:
array_2D.min()

1

In [ ]:
array_2D.sum()

46

### array 모양 변경하기 

In [8]:
reshape_array = np.arange(100)
print(reshape_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


데이터 리쉐입이 중요한이유. 인공지능 데이터의 리쉐입이 중요. 여러데이터가 들어왔을때 데이터의 형태가 맞아줘야함.

In [9]:
reshape_array = reshape_array.reshape(20, -1)  # -1 : 알아서 맞추라는 명령어

print(reshape_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]


In [10]:
reshape_array.shape

(20, 5)

In [11]:
reshape_array.ndim #몇 차원이니?

2

In [12]:
reshape_array.size

100

In [13]:
array_1D = np.arange(0, 100, 5)
print(array_1D)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [14]:
reshape_array_3D = array_1D.reshape(2, 2, 5)
reshape_array_3D

array([[[ 0,  5, 10, 15, 20],
        [25, 30, 35, 40, 45]],

       [[50, 55, 60, 65, 70],
        [75, 80, 85, 90, 95]]])

### numpy array operation

In [18]:
array1 = np.array([[1, 0],
                [0, 1]])
array2 = np.array([[1, 2],
                [3, 4]])

In [19]:
array1 + array2

array([[2, 2],
       [3, 5]])

In [20]:
array1 - array2

array([[ 0, -2],
       [-3, -3]])

In [21]:
array1 * array2

array([[1, 0],
       [0, 4]])

In [22]:
array1 / array2

array([[1.  , 0.  ],
       [0.  , 0.25]])

In [23]:
array1 + 1

array([[2, 1],
       [1, 2]])

In [ ]:
array1 - 1

array([[ 0, -1],
       [-1,  0]])

In [ ]:
array1 * 2

array([[2, 0],
       [0, 2]])

In [ ]:
array1 / 2

array([[0.5, 0. ],
       [0. , 0.5]])

In [25]:
np.dot(array1, array2) #행렬곱

array([[1, 2],
       [3, 4]])

In [27]:
n3 = np.arange(12).reshape(3,4)
print(n3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [26]:
print(n3.max())     # 최대값
print(n3.min())     # 최소값
print(n3.sum())     # 전체 합
print(n3.mean())     # 평균값
print(n3.std())     # 표준편차
print(n3.var())     # 분산
print(n3.cumsum())     # 각 원소의 누적 합
print(n3.cumprod())     # 각 원소의 누적 곱

11
0
66
5.5
3.452052529534663
11.916666666666666
[ 0  1  3  6 10 15 21 28 36 45 55 66]
[0 0 0 0 0 0 0 0 0 0 0 0]


In [28]:
n3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
n3.sum(axis=0)     # 열 합계 colum 가로줄/ axis=0

array([12, 15, 18, 21])

In [ ]:
n3.sum(axis=1)     # 행 합계  row 세로줄/ axis=1

array([ 6, 22, 38])

In [ ]:
n3.max(axis=1)     # 각 행에서 최대값

array([ 3,  7, 11])

In [ ]:
n3.mean(axis=0)     # 각 열의 평균값

array([4., 5., 6., 7.])

In [31]:
n3.cumsum(axis=0)  

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [32]:
n3.cumsum(axis=1)  

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

### array stack

In [33]:
v1 = np.arange(11, 16)
print(v1)
v2 = v1 + 10
print(v2)
v3 = v2 + 10
print(v3)

[11 12 13 14 15]
[21 22 23 24 25]
[31 32 33 34 35]


In [34]:
v = np.vstack((v1, v2))
v = np.vstack((v, v3))
print(v)

[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]]


In [46]:
v = np.array([[11, 12, 13, 14, 15],
              [21, 22, 23, 24, 25],
              [31, 32, 33, 34, 35],
              [41, 42, 43, 44, 45]])

In [ ]:
v[1, 2]

23

In [ ]:
v[1][2]

23

In [ ]:
v[1:3, 1]

array([22, 32])

In [ ]:
v[1, :]

array([21, 22, 23, 24, 25])

In [ ]:
v[:, 1]

array([12, 22, 32, 42])

In [ ]:
Q.array([33,44]) 가 나오게 슬라이싱

In [49]:
v[2,2:4]

array([33, 34])

In [54]:
v[0:,3] # v[row,colum]

array([14, 24, 34, 44])

In [55]:
v [1:3,2:4]

array([[23, 24],
       [33, 34]])